export const authTypes = {
  SET_LOADER: "SET_LOADER",
  CLOSE_LOADER: "CLOSE_LOADER",
  LOGOUT: "LOGOUT",
  SET_TOKEN: "SET_TOKEN",
  REGISTER_ERRORS: "REGISTER_ERRORS",
  LOGIN_ERRORS: "LOGIN_ERRORS",
}
