export const postTypes = {
  CRATE_ERRORS: "CRATE_ERRORS",
  REMOVE_ERRORS: "REMOVE_ERRORS",
  SET_LOADER: "SET_LOADER",
  CLOSE_LOADER: "CLOSE_LOADER",
  REDIRECT_TRUE: "REDIRECT_TRUE",
  REDIRECT_FALSE: "REDIRECT_FALSE",
  SET_MESSAGE: "SET_MESSAGE",
  REMOVE_MESSAGE: "REMOVE_MESSAGE",
  SET_POSTS: "SET_POSTS",
  SET_POST: "SET_POST",
  POST_REQUEST: "POST_REQUEST",
  POST_RESET: "POST_RESET",
};
